name: Run My Content Bot
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # رفعنا النسخة لتجنب التحذيرات
      - name: Install Libs
        run: pip install -U google-genai google-auth google-api-python-client
      - name: Create Credentials
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
      - name: Execute Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python generate_plan.py
